-- ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

CREATE USER TESTUSER IDENTIFIED BY pwd;
GRANT CONNECT TO TESTUSER;
GRANT CREATE TABLE TO TESTUSER;
GRANT CREATE SEQUENCE TO TESTUSER;
ALTER USER TESTUSER QUOTA 100M ON users;

--------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------

CREATE TABLE TESTUSER.DBZ_TEST_TABLE (
    COL_BPCHAR VARCHAR2(30) NOT NULL ENABLE, 
    COL_VARCHAR VARCHAR2(30) NOT NULL ENABLE, 
    COL_FLOAT8 NUMBER, 
    COL_INT4 NUMBER(5,0), 
    COL_NUMERIC NUMBER, 
    COL_INT2 NUMBER(8,0), 
    COL_TEXT VARCHAR2(30),
    COL_TIMESTAMP DATE,
    CONSTRAINT PK_DBZ_TEST_TABLE PRIMARY KEY (COL_BPCHAR, COL_VARCHAR),
    SUPPLEMENTAL LOG DATA (ALL) COLUMNS
);
GRANT SELECT ON TESTUSER.DBZ_TEST_TABLE TO DBZUSER;
-- GRANT SELECT ON TESTUSER.DBZ_TEST_TABLE TO C##DBZUSER;

CREATE TABLE TESTUSER.DBZ_TEST_TABLE_TARGET (
    COL_BPCHAR VARCHAR2(30) NOT NULL ENABLE, 
    COL_VARCHAR VARCHAR2(30) NOT NULL ENABLE, 
    COL_FLOAT8 NUMBER, 
    COL_INT4 NUMBER(5,0), 
    COL_NUMERIC NUMBER, 
    COL_INT2 NUMBER(8,0), 
    COL_TEXT VARCHAR2(30),
    COL_TIMESTAMP DATE,
    CONSTRAINT PK_DBZ_TEST_TABLE_TARGET PRIMARY KEY (COL_BPCHAR, COL_VARCHAR),
    SUPPLEMENTAL LOG DATA (ALL) COLUMNS
);
GRANT SELECT ON TESTUSER.DBZ_TEST_TABLE_TARGET TO DBZUSER;
-- GRANT SELECT ON TESTUSER.DBZ_TEST_TABLE_TARGET TO C##DBZUSER;

CREATE TABLE TESTUSER.DBZ_TEST_PT_TABLE (
    COL_BPCHAR VARCHAR2(30) NOT NULL ENABLE,
    COL_VARCHAR VARCHAR2(30) NOT NULL ENABLE,
    COL_FLOAT8 NUMBER,
    COL_INT4 NUMBER(5,0),
    COL_NUMERIC NUMBER,
    COL_INT2 NUMBER(8,0),
    COL_TEXT VARCHAR2(30),
    COL_TIMESTAMP DATE,
    CONSTRAINT PK_DBZ_TEST_PT_TABLE PRIMARY KEY (COL_BPCHAR, COL_VARCHAR),
    SUPPLEMENTAL LOG DATA (ALL) COLUMNS
) PARTITION BY LIST (COL_BPCHAR) (
    PARTITION P_TEST_1 VALUES ('test_1', 'TEST_1'),
    PARTITION P_TEST_2 VALUES ('test_2', 'TEST_2'),
    PARTITION P_TEST_3 VALUES ('test_3', 'TEST_3'),
    PARTITION P_UNITS VALUES ('1', '2', '3', '4', '5', '6', '7', '8', '9', '0'),
    PARTITION P_ELSE VALUES (DEFAULT)
);
ALTER TABLE TESTUSER.DBZ_TEST_PT_TABLE ENABLE ROW MOVEMENT;
GRANT SELECT ON TESTUSER.DBZ_TEST_PT_TABLE TO DBZUSER;
-- GRANT SELECT ON TESTUSER.DBZ_TEST_PT_TABLE TO C##DBZUSER;

CREATE TABLE TESTUSER.DBZ_TEST_PT_TABLE_TARGET (
    COL_BPCHAR VARCHAR2(30) NOT NULL ENABLE,
    COL_VARCHAR VARCHAR2(30) NOT NULL ENABLE,
    COL_FLOAT8 NUMBER,
    COL_INT4 NUMBER(5,0),
    COL_NUMERIC NUMBER,
    COL_INT2 NUMBER(8,0),
    COL_TEXT VARCHAR2(30),
    COL_TIMESTAMP DATE,
    CONSTRAINT PK_DBZ_TEST_PT_TABLE_TARGET PRIMARY KEY (COL_BPCHAR, COL_VARCHAR),
    SUPPLEMENTAL LOG DATA (ALL) COLUMNS
) PARTITION BY LIST (COL_BPCHAR) (
    PARTITION P_TARGET_TEST_1 VALUES ('test_1', 'TEST_1'),
    PARTITION P_TARGET_TEST_2 VALUES ('test_2', 'TEST_2'),
    PARTITION P_TARGET_TEST_3 VALUES ('test_3', 'TEST_3'),
    PARTITION P_TARGET_UNITS VALUES ('1', '2', '3', '4', '5', '6', '7', '8', '9', '0'),
    PARTITION P_TARGET_ELSE VALUES (DEFAULT)
);
ALTER TABLE TESTUSER.DBZ_TEST_PT_TABLE_TARGET ENABLE ROW MOVEMENT;
GRANT SELECT ON TESTUSER.DBZ_TEST_PT_TABLE_TARGET TO DBZUSER;
-- GRANT SELECT ON TESTUSER.DBZ_TEST_PT_TABLE_TARGET TO C##DBZUSER;

--------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------

CREATE TABLE TESTUSER.DBZ_TEST_TABLE_NPK (
    COL_BPCHAR VARCHAR2(30), 
    COL_VARCHAR VARCHAR2(30), 
    COL_FLOAT8 NUMBER, 
    COL_INT4 NUMBER(5,0), 
    COL_NUMERIC NUMBER, 
    COL_INT2 NUMBER(8,0), 
    COL_TEXT VARCHAR2(30), 
    COL_TIMESTAMP DATE, 
    SUPPLEMENTAL LOG DATA (ALL) COLUMNS
);
GRANT SELECT ON TESTUSER.DBZ_TEST_TABLE_NPK TO DBZUSER;
-- GRANT SELECT ON TESTUSER.DBZ_TEST_TABLE_NPK TO C##DBZUSER;

CREATE TABLE TESTUSER.DBZ_TEST_TABLE_NPK_TARGET (
    COL_BPCHAR VARCHAR2(30), 
    COL_VARCHAR VARCHAR2(30), 
    COL_FLOAT8 NUMBER, 
    COL_INT4 NUMBER(5,0), 
    COL_NUMERIC NUMBER, 
    COL_INT2 NUMBER(8,0), 
    COL_TEXT VARCHAR2(30), 
    COL_TIMESTAMP DATE, 
    SUPPLEMENTAL LOG DATA (ALL) COLUMNS
);
GRANT SELECT ON TESTUSER.DBZ_TEST_TABLE_NPK_TARGET TO DBZUSER;
-- GRANT SELECT ON TESTUSER.DBZ_TEST_TABLE_NPK_TARGET TO C##DBZUSER;

CREATE TABLE TESTUSER.DBZ_TEST_PT_TABLE_NPK (
    COL_BPCHAR VARCHAR2(30) NOT NULL ENABLE,
    COL_VARCHAR VARCHAR2(30) NOT NULL ENABLE,
    COL_FLOAT8 NUMBER,
    COL_INT4 NUMBER(5,0),
    COL_NUMERIC NUMBER,
    COL_INT2 NUMBER(8,0),
    COL_TEXT VARCHAR2(30),
    COL_TIMESTAMP DATE,
    SUPPLEMENTAL LOG DATA (ALL) COLUMNS
) PARTITION BY LIST (COL_BPCHAR) (
    PARTITION P_NPK_TEST_1 VALUES ('test_1', 'TEST_1'),
    PARTITION P_NPK_TEST_2 VALUES ('test_2', 'TEST_2'),
    PARTITION P_NPK_TEST_3 VALUES ('test_3', 'TEST_3'),
    PARTITION P_NPK_UNITS VALUES ('1', '2', '3', '4', '5', '6', '7', '8', '9', '0'),
    PARTITION P_NPK_NULL VALUES (NULL),
    PARTITION P_NPK_ELSE VALUES (DEFAULT)
);
ALTER TABLE TESTUSER.DBZ_TEST_PT_TABLE_NPK ENABLE ROW MOVEMENT;
GRANT SELECT ON TESTUSER.DBZ_TEST_PT_TABLE_NPK TO DBZUSER;
-- GRANT SELECT ON TESTUSER.DBZ_TEST_PT_TABLE_NPK TO C##DBZUSER;

CREATE TABLE TESTUSER.DBZ_TEST_PT_TABLE_NPK_TARGET (
    COL_BPCHAR VARCHAR2(30) NOT NULL ENABLE,
    COL_VARCHAR VARCHAR2(30) NOT NULL ENABLE,
    COL_FLOAT8 NUMBER,
    COL_INT4 NUMBER(5,0),
    COL_NUMERIC NUMBER,
    COL_INT2 NUMBER(8,0),
    COL_TEXT VARCHAR2(30),
    COL_TIMESTAMP DATE,
    SUPPLEMENTAL LOG DATA (ALL) COLUMNS
) PARTITION BY LIST (COL_BPCHAR) (
    PARTITION P_NPK_TARGET_TEST_1 VALUES ('test_1', 'TEST_1'),
    PARTITION P_NPK_TARGET_TEST_2 VALUES ('test_2', 'TEST_2'),
    PARTITION P_NPK_TARGET_TEST_3 VALUES ('test_3', 'TEST_3'),
    PARTITION P_NPK_TARGET_UNITS VALUES ('1', '2', '3', '4', '5', '6', '7', '8', '9', '0'),
    PARTITION P_NPK_TARGET_NULL VALUES (NULL),
    PARTITION P_NPK_TARGET_ELSE VALUES (DEFAULT)
);
ALTER TABLE TESTUSER.DBZ_TEST_PT_TABLE_NPK_TARGET ENABLE ROW MOVEMENT;
GRANT SELECT ON TESTUSER.DBZ_TEST_PT_TABLE_NPK_TARGET TO DBZUSER;
-- GRANT SELECT ON TESTUSER.DBZ_TEST_PT_TABLE_NPK_TARGET TO C##DBZUSER;

--------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------

CREATE TABLE TESTUSER.DBZ_TEST_TABLE_UK (
    COL_BPCHAR VARCHAR2(30),
    COL_VARCHAR VARCHAR2(30),
    COL_FLOAT8 NUMBER,
    COL_INT4 NUMBER(5,0),
    COL_NUMERIC NUMBER,
    COL_INT2 NUMBER(8,0),
    COL_TEXT VARCHAR2(30),
    COL_TIMESTAMP DATE,
    CONSTRAINT UK_DBZ_TEST_TABLE_UK UNIQUE (COL_BPCHAR, COL_VARCHAR),
    SUPPLEMENTAL LOG DATA (ALL) COLUMNS
);
GRANT SELECT ON TESTUSER.DBZ_TEST_TABLE_UK TO DBZUSER;
-- GRANT SELECT ON TESTUSER.DBZ_TEST_TABLE_UK TO C##DBZUSER;

CREATE TABLE TESTUSER.DBZ_TEST_TABLE_UK_TARGET (
    COL_BPCHAR VARCHAR2(30),
    COL_VARCHAR VARCHAR2(30),
    COL_FLOAT8 NUMBER,
    COL_INT4 NUMBER(5,0),
    COL_NUMERIC NUMBER,
    COL_INT2 NUMBER(8,0),
    COL_TEXT VARCHAR2(30),
    COL_TIMESTAMP DATE,
    CONSTRAINT UK_DBZ_TEST_TABLE_TARGET_UK UNIQUE (COL_BPCHAR, COL_VARCHAR),
    SUPPLEMENTAL LOG DATA (ALL) COLUMNS
);
GRANT SELECT ON TESTUSER.DBZ_TEST_TABLE_UK_TARGET TO DBZUSER;
-- GRANT SELECT ON TESTUSER.DBZ_TEST_TABLE_UK_TARGET TO C##DBZUSER;

CREATE TABLE TESTUSER.DBZ_TEST_PT_TABLE_UK (
    COL_BPCHAR VARCHAR2(30),
    COL_VARCHAR VARCHAR2(30),
    COL_FLOAT8 NUMBER,
    COL_INT4 NUMBER(5,0),
    COL_NUMERIC NUMBER,
    COL_INT2 NUMBER(8,0),
    COL_TEXT VARCHAR2(30),
    COL_TIMESTAMP DATE,
    CONSTRAINT UK_DBZ_TEST_PT_TABLE_UK UNIQUE (COL_BPCHAR, COL_VARCHAR),
    SUPPLEMENTAL LOG DATA (ALL) COLUMNS
) PARTITION BY LIST (COL_BPCHAR) (
    PARTITION P_UK_TEST_1 VALUES ('test_1', 'TEST_1'),
    PARTITION P_UK_TEST_2 VALUES ('test_2', 'TEST_2'),
    PARTITION P_UK_TEST_3 VALUES ('test_3', 'TEST_3'),
    PARTITION P_UK_UNITS VALUES ('1', '2', '3', '4', '5', '6', '7', '8', '9', '0'),
    PARTITION P_UK_NULL VALUES (NULL),
    PARTITION P_UK_ELSE VALUES (DEFAULT)
);
ALTER TABLE TESTUSER.DBZ_TEST_PT_TABLE_UK ENABLE ROW MOVEMENT;
GRANT SELECT ON TESTUSER.DBZ_TEST_PT_TABLE_UK TO DBZUSER;
-- GRANT SELECT ON TESTUSER.DBZ_TEST_PT_TABLE_UK TO C##DBZUSER;

CREATE TABLE TESTUSER.DBZ_TEST_PT_TABLE_UK_TARGET (
    COL_BPCHAR VARCHAR2(30),
    COL_VARCHAR VARCHAR2(30),
    COL_FLOAT8 NUMBER,
    COL_INT4 NUMBER(5,0),
    COL_NUMERIC NUMBER,
    COL_INT2 NUMBER(8,0),
    COL_TEXT VARCHAR2(30),
    COL_TIMESTAMP DATE,
    CONSTRAINT UK_DBZ_TEST_PT_TABLE_UK_TARGET UNIQUE (COL_BPCHAR, COL_VARCHAR),
    SUPPLEMENTAL LOG DATA (ALL) COLUMNS
) PARTITION BY LIST (COL_BPCHAR) (
    PARTITION P_UK_TARGET_TEST_1 VALUES ('test_1', 'TEST_1'),
    PARTITION P_UK_TARGET_TEST_2 VALUES ('test_2', 'TEST_2'),
    PARTITION P_UK_TARGET_TEST_3 VALUES ('test_3', 'TEST_3'),
    PARTITION P_UK_TARGET_UNITS VALUES ('1', '2', '3', '4', '5', '6', '7', '8', '9', '0'),
    PARTITION P_UK_TARGET_NULL VALUES (NULL),
    PARTITION P_UK_TARGET_ELSE VALUES (DEFAULT)
);
ALTER TABLE TESTUSER.DBZ_TEST_PT_TABLE_UK_TARGET ENABLE ROW MOVEMENT;
GRANT SELECT ON TESTUSER.DBZ_TEST_PT_TABLE_UK_TARGET TO DBZUSER;
-- GRANT SELECT ON TESTUSER.DBZ_TEST_PT_TABLE_UK_TARGET TO C##DBZUSER;

--------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------

CREATE TABLE TESTUSER.DBZ_TEST_TABLE_DDL (
    IDX         VARCHAR(6),
    INITIAL_COL NUMBER,
    CONSTRAINT PK_DBZ_TEST_TABLE_DDL PRIMARY KEY (IDX, INITIAL_COL)
);
GRANT SELECT ON TESTUSER.DBZ_TEST_TABLE_DDL TO DBZUSER;
DROP TABLE TESTUSER.DBZ_TEST_TABLE;

CREATE TABLE TESTUSER.DBZ_TEST_TABLE_DDL_TARGET (
    IDX         VARCHAR(6),
    INITIAL_COL NUMBER,
    ADDED_COL NUMBER,
    CONSTRAINT PK_DBZ_TEST_TABLE_DDL_TARGET PRIMARY KEY (IDX, INITIAL_COL)
);
GRANT SELECT ON TESTUSER.DBZ_TEST_TABLE_DDL_TARGET TO DBZUSER;
